// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AccountService.proto

package com.middol.grpc;

public interface AccountReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.middol.grpc.AccountReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
