// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AccountService.proto

package com.middol.grpc;

public final class AccountServiceProto {
  private AccountServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_middol_grpc_Account_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_middol_grpc_Account_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_middol_grpc_AccountReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_middol_grpc_AccountReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024AccountService.proto\022\017com.middol.grpc\"" +
      "&\n\007Account\022\016\n\006userId\030\001 \001(\t\022\013\n\003num\030\002 \001(\001\"" +
      "\037\n\014AccountReply\022\017\n\007message\030\001 \001(\t2T\n\016Acco" +
      "untService\022B\n\005debit\022\030.com.middol.grpc.Ac" +
      "count\032\035.com.middol.grpc.AccountReply\"\000B(" +
      "\n\017com.middol.grpcB\023AccountServiceProtoP\001" +
      "b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_middol_grpc_Account_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_middol_grpc_Account_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_middol_grpc_Account_descriptor,
        new java.lang.String[] { "UserId", "Num", });
    internal_static_com_middol_grpc_AccountReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_middol_grpc_AccountReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_middol_grpc_AccountReply_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
