// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StorageService.proto

package com.middol.grpc;

public interface StorageRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.middol.grpc.StorageRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>string commodityCode = 2;</code>
   * @return The commodityCode.
   */
  java.lang.String getCommodityCode();
  /**
   * <code>string commodityCode = 2;</code>
   * @return The bytes for commodityCode.
   */
  com.google.protobuf.ByteString
      getCommodityCodeBytes();

  /**
   * <code>int32 count = 3;</code>
   * @return The count.
   */
  int getCount();
}
